"""Gateway-owned bridge-state persistence contracts and implementations."""

from .idempotency import InMemoryIdempotencyRepository as InMemoryIdempotencyRepository
from .repository_contracts import (
    BindingConflict,
    BindingRepository,
    DeliverySubmissionCapacityError,
    DeliverySubmissionConflict,
    DeliverySubmissionRepository,
    IdempotencyCapacityError,
    IdempotencyClaimStatus,
    IdempotencyRepository,
    ProjectionCheckpointConflict,
    ProjectionRouteConflict,
    ProjectionRouteRepository,
    RequestCorrelationConflict,
    RequestCorrelationRepository,
    TurnReplyCorrelationConflict,
)
from .state_contracts import (
    MAX_DELIVERY_SUBMISSION_DESTINATIONS,
    ConversationBinding,
    DeliveryReservation,
    DeliveryRouteSnapshot,
    DeliverySubmissionRecord,
    DeliverySubmissionState,
    DestinationDeliveryRecord,
    RequestRouteCorrelation,
    RequestRouteState,
    ThreadProjectionRoute,
    TurnReplyCorrelation,
    validate_binding,
    validate_delivery_route_snapshot,
    validate_delivery_submission_destination_count,
    validate_delivery_submission_record,
    validate_projection_route,
    validate_request_route_correlation,
    validate_turn_reply_correlation,
)

__all__ = [
    "BindingConflict",
    "BindingRepository",
    "ConversationBinding",
    "DeliverySubmissionCapacityError",
    "DeliverySubmissionConflict",
    "DeliverySubmissionRepository",
    "DeliveryReservation",
    "DeliveryRouteSnapshot",
    "DeliverySubmissionRecord",
    "DeliverySubmissionState",
    "DestinationDeliveryRecord",
    "IdempotencyCapacityError",
    "IdempotencyClaimStatus",
    "IdempotencyRepository",
    "InMemoryIdempotencyRepository",
    "MAX_DELIVERY_SUBMISSION_DESTINATIONS",
    "ProjectionCheckpointConflict",
    "ProjectionRouteConflict",
    "ProjectionRouteRepository",
    "RequestCorrelationConflict",
    "RequestCorrelationRepository",
    "RequestRouteCorrelation",
    "RequestRouteState",
    "ThreadProjectionRoute",
    "TurnReplyCorrelationConflict",
    "TurnReplyCorrelation",
    "validate_binding",
    "validate_delivery_route_snapshot",
    "validate_delivery_submission_destination_count",
    "validate_delivery_submission_record",
    "validate_projection_route",
    "validate_request_route_correlation",
    "validate_turn_reply_correlation",
]
