"""Stable exact transition facade for the canonical diagnostics owners."""

from .applications.diagnostics import (
    ApplicationArtifactMaterializationDiagnosticFacts,
    ApplicationArtifactMaterializationFailureCode,
    ApplicationDiagnosticFacts,
    ApplicationDiagnosticsProvider,
    ApplicationPresentationDiagnosticFacts,
    ApplicationPresentationFailureCode,
    DiagnosticsProvider,
)
from .gateway.diagnostics import (
    DeliveryOutcomeObserverDiagnosticFacts,
    DeliveryOutcomeObserverFailureCode,
    DiagnosticsSnapshot,
    GatewayDiagnosticFacts,
    InboundContentTransformerDiagnosticFacts,
    InboundContentTransformFailureCode,
    InboundFailurePresentationFailureCode,
    InboundFailurePresenterDiagnosticFacts,
    OutboundPresentationDiagnosticFacts,
    OutboundPresentationFailureCode,
    ProjectionDiagnosticFacts,
    collect_application_diagnostics,
    collect_channel_diagnostics,
    new_diagnostics_snapshot,
    summarize_projection_health,
)
from .interaction.channels.diagnostics import (
    ChannelDiagnosticFacts,
    ChannelDiagnosticsProvider,
)
from .interaction.diagnostics import (
    ConnectionDiagnosticFacts,
    ConnectionDiagnosticState,
    DiagnosticFailureCode,
    QueueDiagnosticFacts,
    QueueDiagnosticName,
)

__all__ = [
    "ConnectionDiagnosticState",
    "DiagnosticFailureCode",
    "QueueDiagnosticName",
    "QueueDiagnosticFacts",
    "ConnectionDiagnosticFacts",
    "ChannelDiagnosticFacts",
    "ChannelDiagnosticsProvider",
    "ApplicationPresentationFailureCode",
    "ApplicationArtifactMaterializationFailureCode",
    "ApplicationDiagnosticFacts",
    "ApplicationPresentationDiagnosticFacts",
    "ApplicationArtifactMaterializationDiagnosticFacts",
    "ApplicationDiagnosticsProvider",
    "DiagnosticsProvider",
    "InboundContentTransformFailureCode",
    "InboundContentTransformerDiagnosticFacts",
    "InboundFailurePresentationFailureCode",
    "InboundFailurePresenterDiagnosticFacts",
    "OutboundPresentationFailureCode",
    "OutboundPresentationDiagnosticFacts",
    "DeliveryOutcomeObserverFailureCode",
    "DeliveryOutcomeObserverDiagnosticFacts",
    "ProjectionDiagnosticFacts",
    "GatewayDiagnosticFacts",
    "DiagnosticsSnapshot",
    "summarize_projection_health",
    "collect_application_diagnostics",
    "collect_channel_diagnostics",
    "new_diagnostics_snapshot",
]
