from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..gateway.delivery.proactive_authorization import (
        DeliveryPrincipal,
        validate_delivery_principal,
    )
    from ..gateway.routing.bindings import (
        BindConversationToProject,
        BindConversationToThread,
        ClearConversationThread,
        ConversationBound,
    )
    from ..interaction.messages import ConversationRef
    from .operations import (
        ApplicationsListed,
        GatewayOperation,
        GatewayOperationFailed,
        GatewayOperationResult,
        GatewayOperationType,
        ListApplications,
        ObserveThread,
        RequestResponseRouted,
        RespondToRequest,
        SelectApplication,
        ThreadObserved,
    )
    from .validators import (
        derive_client_message_id,
        validate_gateway_operation,
        validate_gateway_operation_result,
    )

from ..applications.capabilities import (
    ApplicationCapabilities,
    EventSequenceScope,
    ProjectCapabilities,
    ProjectMode,
    RuntimeCapabilities,
    SupportLevel,
    ThreadCapabilities,
    ThreadDeletionCapability,
    validate_application_capabilities,
)
from ..applications.contract import (
    AcceptedTurn,
    AgentInput,
    AgentMessage,
    ApplicationInputDispatch,
    ApplicationInputOutcomeUnknown,
    ApplicationRef,
    ApplicationSummary,
    InputContinuationPreference,
    InputDisposition,
    Page,
    ProjectRef,
    ProjectSummary,
    ThreadHistory,
    ThreadRef,
    ThreadSnapshot,
    ThreadStatus,
    ThreadSummary,
    TurnCatchup,
    TurnHistoryEntry,
    TurnReplyCorrelationPolicy,
    TurnStatus,
    validate_thread_ref,
)
from ..applications.events import AgentEvent, AgentEventType, validate_agent_event
from ..applications.operations import (
    ActivateNativeThread,
    ApplicationOperation,
    ApplicationOperationFailed,
    ApplicationOperationResult,
    ApplicationOperationType,
    CreateThread,
    DeleteThread,
    GetProject,
    GetThread,
    GetThreadHistory,
    GetThreadStatus,
    GetTurnCatchup,
    InterruptTurn,
    ListProjects,
    ListThreads,
    NativeThreadActivated,
    ProjectRead,
    ProjectsListed,
    RequestResponded,
    RespondRequest,
    ThreadCreated,
    ThreadDeleted,
    ThreadDeletionMode,
    ThreadHistoryRead,
    ThreadRead,
    ThreadsListed,
    ThreadStatusRead,
    TurnCatchupRead,
    TurnInterrupted,
    validate_application_operation,
    validate_application_operation_result,
)
from ..applications.requests import (
    MAX_INTERACTIVE_REQUEST_CHOICES,
    MAX_INTERACTIVE_REQUEST_QUESTIONS,
    ApprovalRequest,
    ApprovalResponse,
    ApprovalResponseShape,
    InteractiveRequest,
    InteractiveRequestKind,
    RequestChoice,
    RequestDuplicateError,
    RequestRef,
    RequestResolution,
    RequestResolutionStatus,
    RequestResolvedError,
    RequestResponse,
    RequestResponseShape,
    RequestStaleError,
    UserInputQuestion,
    UserInputQuestionShape,
    UserInputRequest,
    UserInputResponse,
    UserInputResponseShape,
    derive_request_response_shape,
    validate_interactive_request,
    validate_request_ref,
    validate_request_resolution,
    validate_request_response,
    validate_request_response_shape,
)
from ..interaction.media import (
    AttachmentContent,
    AttachmentGrouping,
    AttachmentHandle,
    AttachmentSource,
    AttachmentSourceKind,
    LocalPath,
    RemoteUrl,
)
from ..interaction.messages import (
    Content,
    ConversationRef,
    InboundMessage,
    MessageRole,
    Metadata,
    OutboundMessage,
    TextContent,
    TextFormat,
    TextLengthUnit,
)
from ..interaction.operations import (
    ContractError,
    ContractViolation,
    OperationErrorCode,
    OperationResultStatus,
    operation_error,
    require_identifier,
)

_BINDING_EXPORTS = frozenset(
    {
        "BindConversationToProject",
        "BindConversationToThread",
        "ClearConversationThread",
        "ConversationBound",
    }
)
_GATEWAY_OPERATION_EXPORTS = frozenset(
    {
        "ApplicationsListed",
        "GatewayOperation",
        "GatewayOperationFailed",
        "GatewayOperationResult",
        "GatewayOperationType",
        "ListApplications",
        "ObserveThread",
        "RequestResponseRouted",
        "RespondToRequest",
        "SelectApplication",
        "ThreadObserved",
    }
)
_GATEWAY_VALIDATOR_EXPORTS = frozenset(
    {
        "derive_client_message_id",
        "validate_gateway_operation",
        "validate_gateway_operation_result",
    }
)

__all__ = [
    "AcceptedTurn",
    "AgentEvent",
    "AgentEventType",
    "AgentInput",
    "AgentMessage",
    "ApplicationInputDispatch",
    "ApplicationInputOutcomeUnknown",
    "ApprovalRequest",
    "ApprovalResponseShape",
    "ApplicationCapabilities",
    "ApplicationRef",
    "ApplicationSummary",
    "AttachmentHandle",
    "AttachmentContent",
    "AttachmentGrouping",
    "AttachmentSource",
    "AttachmentSourceKind",
    "Content",
    "ContractError",
    "ContractViolation",
    "ConversationRef",
    "DeliveryPrincipal",
    "EventSequenceScope",
    "InputContinuationPreference",
    "InputDisposition",
    "InboundMessage",
    "InteractiveRequest",
    "InteractiveRequestKind",
    "LocalPath",
    "MAX_INTERACTIVE_REQUEST_CHOICES",
    "MAX_INTERACTIVE_REQUEST_QUESTIONS",
    "MessageRole",
    "Metadata",
    "OutboundMessage",
    "ActivateNativeThread",
    "ApplicationOperation",
    "ApplicationOperationFailed",
    "ApplicationOperationResult",
    "ApplicationOperationType",
    "ApplicationsListed",
    "ApprovalResponse",
    "BindConversationToProject",
    "BindConversationToThread",
    "ClearConversationThread",
    "ConversationBound",
    "CreateThread",
    "DeleteThread",
    "GatewayOperation",
    "GatewayOperationFailed",
    "GatewayOperationResult",
    "GatewayOperationType",
    "GetProject",
    "GetThread",
    "GetThreadHistory",
    "GetThreadStatus",
    "GetTurnCatchup",
    "InterruptTurn",
    "ListApplications",
    "ListProjects",
    "ListThreads",
    "NativeThreadActivated",
    "ObserveThread",
    "OperationResultStatus",
    "OperationErrorCode",
    "RequestDuplicateError",
    "RequestResolvedError",
    "RequestStaleError",
    "Page",
    "ProjectCapabilities",
    "ProjectMode",
    "ProjectRef",
    "ProjectSummary",
    "RemoteUrl",
    "ProjectRead",
    "ProjectsListed",
    "RequestResponded",
    "RequestResponseRouted",
    "RequestResponse",
    "RequestChoice",
    "RequestResolution",
    "RequestResolutionStatus",
    "RequestRef",
    "RequestResponseShape",
    "RespondRequest",
    "RespondToRequest",
    "RuntimeCapabilities",
    "SupportLevel",
    "SelectApplication",
    "TextContent",
    "TextFormat",
    "TextLengthUnit",
    "ThreadCapabilities",
    "ThreadCreated",
    "ThreadDeleted",
    "ThreadDeletionCapability",
    "ThreadDeletionMode",
    "ThreadHistoryRead",
    "ThreadObserved",
    "ThreadHistory",
    "ThreadRead",
    "ThreadRef",
    "ThreadSnapshot",
    "ThreadStatus",
    "ThreadSummary",
    "ThreadsListed",
    "ThreadStatusRead",
    "TurnCatchup",
    "TurnCatchupRead",
    "TurnHistoryEntry",
    "TurnReplyCorrelationPolicy",
    "TurnInterrupted",
    "TurnStatus",
    "UserInputResponse",
    "UserInputQuestion",
    "UserInputQuestionShape",
    "UserInputRequest",
    "UserInputResponseShape",
    "derive_client_message_id",
    "derive_request_response_shape",
    "operation_error",
    "require_identifier",
    "validate_application_capabilities",
    "validate_agent_event",
    "validate_application_operation",
    "validate_application_operation_result",
    "validate_delivery_principal",
    "validate_gateway_operation",
    "validate_gateway_operation_result",
    "validate_interactive_request",
    "validate_request_resolution",
    "validate_request_ref",
    "validate_request_response",
    "validate_request_response_shape",
    "validate_thread_ref",
]


def __getattr__(name: str) -> object:
    if name in _BINDING_EXPORTS:
        module = import_module("..gateway.routing.bindings", __name__)
    elif name in _GATEWAY_OPERATION_EXPORTS:
        module = import_module(".operations", __name__)
    elif name in _GATEWAY_VALIDATOR_EXPORTS:
        module = import_module(".validators", __name__)
    elif name in {"DeliveryPrincipal", "validate_delivery_principal"}:
        from ..gateway.delivery.proactive_authorization import (
            DeliveryPrincipal,
            validate_delivery_principal,
        )

        value = DeliveryPrincipal if name == "DeliveryPrincipal" else validate_delivery_principal
        globals()[name] = value
        return value
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(module, name)
    globals()[name] = value
    return value
